-- Uncomment the backup tables you want to drop

-- DROP TABLE FCM_FUNCOES_BACKUP;
-- DROP TABLE FCM_USUARIOS_FUNCOES_BACKUP;
-- DROP TABLE FCM_COMERCIANTES_BACKUP;
-- DROP TABLE FCM_ENTREGADORES_BACKUP;
-- DROP TABLE FCM_PEDIDOS_BACKUP;
-- DROP TABLE FCM_PRODUTOS_FOTOS_BACKUP;
-- DROP TABLE FCM_PEDIDOS_PRODUTOS_BACKUP; // A TABELA ATUAL TEM O NOME DE FCM_PRODUTOS_DOS_PEDIDOS
-- DROP TABLE FCM_PRODUTOS_BACKUP;
