-- MySQL Script generated by MySQL Workbench
-- Mon May  8 17:51:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FCM
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FCM` ;

-- -----------------------------------------------------
-- Schema FCM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FCM` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `FCM` ;

-- -----------------------------------------------------
-- Table `FCM`.`FCM_CATEGORIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_CATEGORIAS` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_CATEGORIAS` (
  `CAT_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `CAT_NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CAT_CODIGO`),
  UNIQUE INDEX `CAT_NOME_UNIQUE` (`CAT_NOME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_USUARIOS` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_USUARIOS` (
  `USU_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `USU_NOME` VARCHAR(45) NOT NULL,
  `USU_NASCIMENTO` DATE NOT NULL,
  `USU_CPF` VARCHAR(11) NOT NULL,
  `USU_EMAIL` VARCHAR(256) NOT NULL,
  `USU_TELEFONE` VARCHAR(11) NOT NULL,
  `USU_FOTO` VARCHAR(45) NULL DEFAULT NULL,
  `USU_SENHA` VARCHAR(45) NOT NULL,
  `USU_APELIDO` VARCHAR(45) NULL,
  `USU_DESCRICAO` VARCHAR(250) NULL,
  PRIMARY KEY (`USU_CODIGO`),
  UNIQUE INDEX `USU_EMAIL_UNIQUE` (`USU_EMAIL` ASC) VISIBLE,
  UNIQUE INDEX `USU_CPF_UNIQUE` (`USU_CPF` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_PRODUTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_PRODUTOS` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_PRODUTOS` (
  `PRO_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `PRO_NOME` VARCHAR(45) NOT NULL,
  `PRO_VALOR` DECIMAL NOT NULL,
  `PRO_QUANTIDADE_DISPONIVEL` INT NOT NULL,
  `PRO_DESCRICAO` VARCHAR(500) NULL DEFAULT NULL,
  `PRO_CAT_CODIGO` INT NOT NULL,
  `PRO_CMT_CODIGO` INT NOT NULL,
  PRIMARY KEY (`PRO_CODIGO`),
  INDEX `fk_FCM_PRODUTOS_FCM_CATEGORIAS1_idx` (`PRO_CAT_CODIGO` ASC) VISIBLE,
  INDEX `fk_FCM_PRODUTOS_FCM_USUARIOS1_idx` (`PRO_CMT_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_FCM_PRODUTOS_FCM_CATEGORIAS1`
    FOREIGN KEY (`PRO_CAT_CODIGO`)
    REFERENCES `FCM`.`FCM_CATEGORIAS` (`CAT_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FCM_PRODUTOS_FCM_USUARIOS1`
    FOREIGN KEY (`PRO_CMT_CODIGO`)
    REFERENCES `FCM`.`FCM_USUARIOS` (`USU_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_PRODUTOS_FOTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_PRODUTOS_FOTOS` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_PRODUTOS_FOTOS` (
  `PFT_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `PFT_CAMINHO` VARCHAR(45) NOT NULL,
  `PFT_PRO_CODIGO` INT NOT NULL,
  PRIMARY KEY (`PFT_CODIGO`),
  INDEX `fk_FCM_PRODUTOS_FOTOS_FCM_PRODUTOS1_idx` (`PFT_PRO_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_FCM_PRODUTOS_FOTOS_FCM_PRODUTOS1`
    FOREIGN KEY (`PFT_PRO_CODIGO`)
    REFERENCES `FCM`.`FCM_PRODUTOS` (`PRO_CODIGO`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_PAISES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_PAISES` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_PAISES` (
  `PAIS_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `PAIS_NOME` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`PAIS_CODIGO`),
  UNIQUE INDEX `PAIS_NOME_UNIQUE` (`PAIS_NOME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_UNIDADES_FEDERATIVAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_UNIDADES_FEDERATIVAS` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_UNIDADES_FEDERATIVAS` (
  `UNF_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `UNF_NOME` VARCHAR(60) NOT NULL,
  `UNF_PAIS_CODIGO` INT NOT NULL,
  PRIMARY KEY (`UNF_CODIGO`),
  INDEX `fk_FCM_ESTADO_FCM_PAIS1_idx` (`UNF_PAIS_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_FCM_ESTADO_FCM_PAIS1`
    FOREIGN KEY (`UNF_PAIS_CODIGO`)
    REFERENCES `FCM`.`FCM_PAISES` (`PAIS_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_LOCALIDADES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_LOCALIDADES` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_LOCALIDADES` (
  `LOC_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `LOC_NOME` VARCHAR(60) NOT NULL,
  `LOC_UNF_CODIGO` INT NOT NULL,
  PRIMARY KEY (`LOC_CODIGO`),
  INDEX `fk_FCM_CIDADE_FCM_ESTADO1_idx` (`LOC_UNF_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_FCM_CIDADE_FCM_ESTADO1`
    FOREIGN KEY (`LOC_UNF_CODIGO`)
    REFERENCES `FCM`.`FCM_UNIDADES_FEDERATIVAS` (`UNF_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_LOGRADOUROS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_LOGRADOUROS` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_LOGRADOUROS` (
  `LOG_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `LOG_NOME` VARCHAR(60) NOT NULL,
  `LOG_LOC_CODIGO` INT NOT NULL,
  PRIMARY KEY (`LOG_CODIGO`),
  INDEX `fk_FCM_LOGRADOURO_FCM_LOCALIDADE1_idx` (`LOG_LOC_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_FCM_LOGRADOURO_FCM_LOCALIDADE1`
    FOREIGN KEY (`LOG_LOC_CODIGO`)
    REFERENCES `FCM`.`FCM_LOCALIDADES` (`LOC_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_LOGRADOUROS_DOS_USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_LOGRADOUROS_DOS_USUARIOS` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_LOGRADOUROS_DOS_USUARIOS` (
  `LDU_USU_CODIGO` INT NOT NULL,
  `LDU_LOG_CODIGO` INT NOT NULL,
  `LDU_NUMERO` INT NULL,
  `LDU_COMPLEMENTO` VARCHAR(45) NULL,
  PRIMARY KEY (`LDU_USU_CODIGO`, `LDU_LOG_CODIGO`),
  INDEX `fk_FCM_USUARIOS_has_FCM_LOGRADOURO_FCM_LOGRADOURO1_idx` (`LDU_LOG_CODIGO` ASC) VISIBLE,
  INDEX `fk_FCM_USUARIOS_has_FCM_LOGRADOURO_FCM_USUARIOS1_idx` (`LDU_USU_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_FCM_USUARIOS_has_FCM_LOGRADOURO_FCM_USUARIOS1`
    FOREIGN KEY (`LDU_USU_CODIGO`)
    REFERENCES `FCM`.`FCM_USUARIOS` (`USU_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FCM_USUARIOS_has_FCM_LOGRADOURO_FCM_LOGRADOURO1`
    FOREIGN KEY (`LDU_LOG_CODIGO`)
    REFERENCES `FCM`.`FCM_LOGRADOUROS` (`LOG_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_CARRINHO_DE_COMPRAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_CARRINHO_DE_COMPRAS` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_CARRINHO_DE_COMPRAS` (
  `CDC_PRO_CODIGO` INT NOT NULL,
  `CDC_USU_CODIGO` INT NOT NULL,
  `CDC_QUANTIDADE` INT NOT NULL,
  `CDC_SELECIONADO` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`CDC_PRO_CODIGO`, `CDC_USU_CODIGO`),
  INDEX `fk_FCM_PRODUTOS_has_FCM_USUARIOS_FCM_USUARIOS1_idx` (`CDC_USU_CODIGO` ASC) VISIBLE,
  INDEX `fk_FCM_PRODUTOS_has_FCM_USUARIOS_FCM_PRODUTOS1_idx` (`CDC_PRO_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_FCM_PRODUTOS_has_FCM_USUARIOS_FCM_PRODUTOS1`
    FOREIGN KEY (`CDC_PRO_CODIGO`)
    REFERENCES `FCM`.`FCM_PRODUTOS` (`PRO_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FCM_PRODUTOS_has_FCM_USUARIOS_FCM_USUARIOS1`
    FOREIGN KEY (`CDC_USU_CODIGO`)
    REFERENCES `FCM`.`FCM_USUARIOS` (`USU_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_COMERCIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_COMERCIOS` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_COMERCIOS` (
  `CMR_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `CMR_NOME` VARCHAR(45) NOT NULL,
  `CMR_DESCRICAO` VARCHAR(250) NULL,
  `CMR_FOTO_PERFIL` VARCHAR(45) NULL,
  `CMR_NUMERO` INT NULL,
  `CMR_COMPLEMENTO_ENDERECO` VARCHAR(45) NULL,
  `CMR_USU_CODIGO` INT NOT NULL,
  `CMR_LOG_CODIGO` INT NOT NULL,
  PRIMARY KEY (`CMR_CODIGO`),
  INDEX `fk_FCM_COMERCIO_FCM_USUARIOS1_idx` (`CMR_USU_CODIGO` ASC) VISIBLE,
  INDEX `fk_FCM_COMERCIO_FCM_LOGRADOURO1_idx` (`CMR_LOG_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_FCM_COMERCIO_FCM_USUARIOS1`
    FOREIGN KEY (`CMR_USU_CODIGO`)
    REFERENCES `FCM`.`FCM_USUARIOS` (`USU_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FCM_COMERCIO_FCM_LOGRADOURO1`
    FOREIGN KEY (`CMR_LOG_CODIGO`)
    REFERENCES `FCM`.`FCM_LOGRADOUROS` (`LOG_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_COMERCIO_FOTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_COMERCIO_FOTOS` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_COMERCIO_FOTOS` (
  `CFT_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `CFT_CAMINHO` VARCHAR(45) NOT NULL,
  `CFT_CMR_CODIGO` INT NOT NULL,
  PRIMARY KEY (`CFT_CODIGO`),
  INDEX `fk_FCM_COMERCIO_FOTOS_FCM_COMERCIO1_idx` (`CFT_CMR_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_FCM_COMERCIO_FOTOS_FCM_COMERCIO1`
    FOREIGN KEY (`CFT_CMR_CODIGO`)
    REFERENCES `FCM`.`FCM_COMERCIOS` (`CMR_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FCM`.`FCM_COMERCIO_TELEFONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCM`.`FCM_COMERCIO_TELEFONES` ;

CREATE TABLE IF NOT EXISTS `FCM`.`FCM_COMERCIO_TELEFONES` (
  `TEL_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `TEL_NUMERO` VARCHAR(11) NOT NULL,
  `TEL_CMR_CODIGO` INT NOT NULL,
  PRIMARY KEY (`TEL_CODIGO`),
  INDEX `fk_FCM_TELEFONES_FCM_COMERCIO1_idx` (`TEL_CMR_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_FCM_TELEFONES_FCM_COMERCIO1`
    FOREIGN KEY (`TEL_CMR_CODIGO`)
    REFERENCES `FCM`.`FCM_COMERCIOS` (`CMR_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO FCM_PAISES (PAIS_NOME)
VALUES 
("Afeganistão"),
("África do Sul"),
("Albânia"),
("Alemanha"),
("Andorra"),
("Angola"),
("Anguila"),
("Antártica"),
("Antígua e Barbuda"),
("Arábia Saudita"),
("Argélia"),
("Argentina"),
("Armênia"),
("Aruba"),
("Austrália"),
("Áustria"),
("Azerbaijão"),
("Bahamas"),
("Bahrein"),
("Bangladesh"),
("Barbados"),
("Belarus"),
("Bélgica"),
("Belize"),
("Benin"),
("Bermudas"),
("Bolívia"),
("Bósnia e Herzegovina"),
("Botsuana"),
("Brasil"),
("Brunei"),
("Bulgária"),
("Burkina Faso"),
("Burundi"),
("Butão"),
("Cabo Verde"),
("Camarões"),
("Camboja"),
("Canadá"),
("Cazaquistão"),
("Chade"),
("Chile"),
("China"),
("Chipre"),
("Cidade do Vaticano"),
("Cingapura"),
("Colômbia"),
("Comores"),
("Coréia do Norte"),
("Coréia do Sul"),
("Costa do Marfim"),
("Costa Rica"),
("Croácia"),
("Cuba"),
("Curaçao"),
("Dinamarca"),
("Djibouti"),
("Dominica"),
("Egito"),
("El Salvador"),
("Emirados Árabes Unidos"),
("Equador"),
("Eritreia"),
("Eslováquia"),
("Eslovênia"),
("Espanha"),
("Estados Federados da Micronésia"),
("Estados Unidos da América"),
("Estônia"),
("Eswatini"),
("Etiópia"),
("Fiji"),
("Filipinas"),
("Finlândia"),
("França"),
("Gabão"),
("Gâmbia"),
("Gana"),
("Geórgia"),
("Geórgia do Sul e as Ilhas Sandwich do Sul"),
("Gibraltar"),
("Grécia"),
("Grenada"),
("Gronelândia"),
("Guadalupe"),
("Guam"),
("Guatemala"),
("Guernsey"),
("Guiana"),
("Guiana Francesa"),
("Guiné"),
("Guiné Equatorial"),
("Guiné-Bissau"),
("Haiti"),
("Honduras"),
("Hong Kong"),
("Hungria"),
("Iêmen"),
("Ilha Bouvet"),
("Ilha da Reunião"),
("Ilha de Man"),
("Ilha de Natal"),
("Ilha Norfolk"),
("Ilhas Åland"),
("Ilhas Cayman"),
("Ilhas Cocos"),
("Ilhas Cook"),
("Ilhas Faroe"),
("Ilhas Malvinas"),
("Ilhas Marianas do Norte"),
("Ilhas Marshall"),
("Ilhas Menores Distantes dos Estados Unidos"),
("Ilhas Pitcairn"),
("Ilhas Salomão"),
("Ilhas Turcas e Caicos"),
("Ilhas Virgens (Reino Unido)"),
("Ilhas Virgens dos Estados Unidos"),
("Índia"),
("Indonésia"),
("Irã"),
("Iraque"),
("Irlanda"),
("Islândia"),
("Israel"),
("Itália"),
("Jamaica"),
("Japão"),
("Jersey"),
("Jordânia"),
("Kiribati"),
("Kosovo"),
("Kuwait"),
("Laos"),
("Lesotho"),
("Letônia"),
("Líbano"),
("Libéria"),
("Líbia"),
("Liechtenstein"),
("Lituânia"),
("Luxemburgo"),
("Macau"),
("Madagascar"),
("Malásia"),
("Malauí"),
("Maldivas"),
("Mali"),
("Malta"),
("Marrocos"),
("Martinica"),
("Maurício"),
("Mauritânia"),
("Mayotte"),
("México"),
("Mianmar"),
("Moçambique"),
("Moldávia"),
("Mongólia"),
("Montenegro"),
("Montserrat"),
("Namíbia"),
("Nauru"),
("Nepal"),
("Nicarágua"),
("Níger"),
("Nigéria"),
("Niue"),
("Norte da Macedônia"),
("Noruega"),
("Nova Caledônia"),
("Nova Zelândia"),
("Omã"),
("Ouvido e Ilhas McDonald"),
("Países Baixos"),
("Países Baixos Caribenhos"),
("Palau"),
("Palestina"),
("Panamá"),
("Papua Nova Guiné"),
("Paquistão"),
("Paraguai"),
("Peru"),
("Polinésia Francesa"),
("Polônia"),
("Porto Rico"),
("Portugal"),
("Principado de Mônaco"),
("Qatar"),
("Quênia"),
("Quirguizistão"),
("Reino Unido"),
("República Centro-Africana"),
("República Democrática do Congo"),
("República do Congo"),
("República Dominicana"),
("Romênia"),
("Ruanda"),
("Rússia"),
("Saara Ocidental"),
("Samoa"),
("Samoa Americana"),
("Santa Helena, Ascensão e Tristão da Cunha"),
("Santa Lúcia"),
("Santo Bartolomeu"),
("São Marino"),
("São Martinho"),
("São Pedro e Miquelon"),
("São Tomé e Príncipe"),
("São Vicente e as Granadinas"),
("Senegal"),
("Serra Leoa"),
("Sérvia"),
("Seychelles"),
("Sint Maarten"),
("Síria"),
("Somália"),
("Sri Lanka"),
("St. Kitts e Nevis"),
("Sudão"),
("Sudão do Sul"),
("Suécia"),
("Suíça"),
("Suriname"),
("Svalbard e Jan Mayen"),
("Tailândia"),
("Taiwan"),
("Tajiquistão"),
("Tanzânia"),
("Tcheca"),
("Território Britânico do Oceano Índico"),
("Territórios Franceses do Sul e Antártico"),
("Timor Leste"),
("Togo"),
("Tokelau"),
("Tonga"),
("Trinidad e Tobago"),
("Tunísia"),
("Turcomenistão"),
("Turquia"),
("Tuvalu"),
("Ucrânia"),
("Uganda"),
("Uruguai"),
("Uzbequistão"),
("Vanuatu"),
("Venezuela"),
("Vietnã"),
("Wallis e Futuna"),
("Zâmbia"),
("Zimbábue");


INSERT INTO FCM_UNIDADES_FEDERATIVAS (UNF_NOME, UNF_PAIS_CODIGO)
VALUES 
("AC", 30),
("AL", 30),
("AP", 30),
("AM", 30),
("BA", 30),
("CE", 30),
("DF", 30),
("ES", 30),
("GO", 30),
("MA", 30),
("MT", 30),
("MS", 30),
("MG", 30),
("PA", 30),
("PB", 30),
("PR", 30),
("PE", 30),
("PI", 30),
("RJ", 30),
("RN", 30),
("RS", 30),
("RO", 30),
("RR", 30),
("SC", 30),
("SP", 30),
("SE", 30),
("TO", 30);

INSERT INTO FCM_CATEGORIAS (CAT_NOME)
VALUES 
("Roupas"),
("Utensílios"),
("Alimentos"),
("Outros");
