INSERT INTO FCM_PAISES (PAIS_NOME)
VALUES 
("Afeganistão"),
("África do Sul"),
("Albânia"),
("Alemanha"),
("Andorra"),
("Angola"),
("Anguila"),
("Antártica"),
("Antígua e Barbuda"),
("Arábia Saudita"),
("Argélia"),
("Argentina"),
("Armênia"),
("Aruba"),
("Austrália"),
("Áustria"),
("Azerbaijão"),
("Bahamas"),
("Bahrein"),
("Bangladesh"),
("Barbados"),
("Belarus"),
("Bélgica"),
("Belize"),
("Benin"),
("Bermudas"),
("Bolívia"),
("Bósnia e Herzegovina"),
("Botsuana"),
("Brasil"),
("Brunei"),
("Bulgária"),
("Burkina Faso"),
("Burundi"),
("Butão"),
("Cabo Verde"),
("Camarões"),
("Camboja"),
("Canadá"),
("Cazaquistão"),
("Chade"),
("Chile"),
("China"),
("Chipre"),
("Cidade do Vaticano"),
("Cingapura"),
("Colômbia"),
("Comores"),
("Coréia do Norte"),
("Coréia do Sul"),
("Costa do Marfim"),
("Costa Rica"),
("Croácia"),
("Cuba"),
("Curaçao"),
("Dinamarca"),
("Djibouti"),
("Dominica"),
("Egito"),
("El Salvador"),
("Emirados Árabes Unidos"),
("Equador"),
("Eritreia"),
("Eslováquia"),
("Eslovênia"),
("Espanha"),
("Estados Federados da Micronésia"),
("Estados Unidos da América"),
("Estônia"),
("Eswatini"),
("Etiópia"),
("Fiji"),
("Filipinas"),
("Finlândia"),
("França"),
("Gabão"),
("Gâmbia"),
("Gana"),
("Geórgia"),
("Geórgia do Sul e as Ilhas Sandwich do Sul"),
("Gibraltar"),
("Grécia"),
("Grenada"),
("Gronelândia"),
("Guadalupe"),
("Guam"),
("Guatemala"),
("Guernsey"),
("Guiana"),
("Guiana Francesa"),
("Guiné"),
("Guiné Equatorial"),
("Guiné-Bissau"),
("Haiti"),
("Honduras"),
("Hong Kong"),
("Hungria"),
("Iêmen"),
("Ilha Bouvet"),
("Ilha da Reunião"),
("Ilha de Man"),
("Ilha de Natal"),
("Ilha Norfolk"),
("Ilhas Åland"),
("Ilhas Cayman"),
("Ilhas Cocos"),
("Ilhas Cook"),
("Ilhas Faroe"),
("Ilhas Malvinas"),
("Ilhas Marianas do Norte"),
("Ilhas Marshall"),
("Ilhas Menores Distantes dos Estados Unidos"),
("Ilhas Pitcairn"),
("Ilhas Salomão"),
("Ilhas Turcas e Caicos"),
("Ilhas Virgens (Reino Unido)"),
("Ilhas Virgens dos Estados Unidos"),
("Índia"),
("Indonésia"),
("Irã"),
("Iraque"),
("Irlanda"),
("Islândia"),
("Israel"),
("Itália"),
("Jamaica"),
("Japão"),
("Jersey"),
("Jordânia"),
("Kiribati"),
("Kosovo"),
("Kuwait"),
("Laos"),
("Lesotho"),
("Letônia"),
("Líbano"),
("Libéria"),
("Líbia"),
("Liechtenstein"),
("Lituânia"),
("Luxemburgo"),
("Macau"),
("Madagascar"),
("Malásia"),
("Malauí"),
("Maldivas"),
("Mali"),
("Malta"),
("Marrocos"),
("Martinica"),
("Maurício"),
("Mauritânia"),
("Mayotte"),
("México"),
("Mianmar"),
("Moçambique"),
("Moldávia"),
("Mongólia"),
("Montenegro"),
("Montserrat"),
("Namíbia"),
("Nauru"),
("Nepal"),
("Nicarágua"),
("Níger"),
("Nigéria"),
("Niue"),
("Norte da Macedônia"),
("Noruega"),
("Nova Caledônia"),
("Nova Zelândia"),
("Omã"),
("Ouvido e Ilhas McDonald"),
("Países Baixos"),
("Países Baixos Caribenhos"),
("Palau"),
("Palestina"),
("Panamá"),
("Papua Nova Guiné"),
("Paquistão"),
("Paraguai"),
("Peru"),
("Polinésia Francesa"),
("Polônia"),
("Porto Rico"),
("Portugal"),
("Principado de Mônaco"),
("Qatar"),
("Quênia"),
("Quirguizistão"),
("Reino Unido"),
("República Centro-Africana"),
("República Democrática do Congo"),
("República do Congo"),
("República Dominicana"),
("Romênia"),
("Ruanda"),
("Rússia"),
("Saara Ocidental"),
("Samoa"),
("Samoa Americana"),
("Santa Helena, Ascensão e Tristão da Cunha"),
("Santa Lúcia"),
("Santo Bartolomeu"),
("São Marino"),
("São Martinho"),
("São Pedro e Miquelon"),
("São Tomé e Príncipe"),
("São Vicente e as Granadinas"),
("Senegal"),
("Serra Leoa"),
("Sérvia"),
("Seychelles"),
("Sint Maarten"),
("Síria"),
("Somália"),
("Sri Lanka"),
("St. Kitts e Nevis"),
("Sudão"),
("Sudão do Sul"),
("Suécia"),
("Suíça"),
("Suriname"),
("Svalbard e Jan Mayen"),
("Tailândia"),
("Taiwan"),
("Tajiquistão"),
("Tanzânia"),
("Tcheca"),
("Território Britânico do Oceano Índico"),
("Territórios Franceses do Sul e Antártico"),
("Timor Leste"),
("Togo"),
("Tokelau"),
("Tonga"),
("Trinidad e Tobago"),
("Tunísia"),
("Turcomenistão"),
("Turquia"),
("Tuvalu"),
("Ucrânia"),
("Uganda"),
("Uruguai"),
("Uzbequistão"),
("Vanuatu"),
("Venezuela"),
("Vietnã"),
("Wallis e Futuna"),
("Zâmbia"),
("Zimbábue");


INSERT INTO FCM_UNIDADES_FEDERATIVAS (UNF_NOME, UNF_PAIS_CODIGO)
VALUES 
("AC", 30),
("AL", 30),
("AP", 30),
("AM", 30),
("BA", 30),
("CE", 30),
("DF", 30),
("ES", 30),
("GO", 30),
("MA", 30),
("MT", 30),
("MS", 30),
("MG", 30),
("PA", 30),
("PB", 30),
("PR", 30),
("PE", 30),
("PI", 30),
("RJ", 30),
("RN", 30),
("RS", 30),
("RO", 30),
("RR", 30),
("SC", 30),
("SP", 30),
("SE", 30),
("TO", 30);

INSERT INTO FCM_CATEGORIAS (CAT_NOME)
VALUES 
("Roupas"),
("Utensílios"),
("Alimentos"),
("Outros");
